unbind C-b
set -g prefix C-a
#bind-key C-a send-prefix
bind-key a send-prefix

set -g history-limit 5000                               # Размер буфера в линиях

set -g set-titles on                                    # Разрешить смену заголовков в оконном менеджере
set -g set-titles-string "tmux.#I.#W"                   # Формат строки заголовка

bind-key k confirm kill-window                          # Подтверждать уничтожение окна
bind-key K confirm kill-server                          # Подтверждать уничтожение сервера


setw -g monitor-activity on                             # Информировать когда есть активность в окнах
set -g visual-activity on                               # Показывать статусное сообщение при активности в каком либо окне

bind-key k confirm kill-window                          # Подтверждать уничтожение окна
bind-key K confirm kill-server                          # Подтверждать уничтожение сервера

# Статусбар ------------------------------------------------------------------

set -g display-time 2000                                # Время в миллисекундах, сколько будут отображаться сообщения (в статусбаре к примеру)

# Цвета  ---------------------------------------------------------------------

# Цвета статусбара
set -g status-fg white
set -g status-bg default
set -g status-attr default

# Цвета заголовков окон
set-window-option -g window-status-fg cyan
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# Цвета активных окон
set-window-option -g window-status-current-fg white
set-window-option -g window-status-current-bg default   # Выделение активного окна белым цветом
set-window-option -g window-status-current-attr bright

# Цвета командной строки
set -g message-fg white
set -g message-bg black
set -g message-attr bright

# Навигация в командной строке, и в списке окон как в vi
set -g status-keys vi
setw -g mode-keys vi

# Начиная с версии 2.6 tmux поменял синтаксис.
# Выделение желтым нажатием на "v".
# bind-key -t vi-copy 'v' begin-selection
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
# Копирование выделенного желтым нажатием на "y".
# bind-key -t vi-copy 'y' copy-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection

#bind-key -n C-n next                                    # Следующий таб
#bind-key -n C-p prev                                    # Предыдущий таб

#bind y run-shell "tmux show-buffer | xclip -sel clip -i" \; display-message "Copied tmux buffer to system clipboard"


# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Disable automatic rename windows names.
set-option -g allow-rename off

# Enable Tmux Resurrect plugin.
run-shell /home/mobaxterm/.tmux-resurrect/resurrect.tmux

