#!/usr/bin/perl
#
# This abuses the fact that Puppet writes the date/time it modifies
# a crontab to the that file.  Then we check if the change occurred at
# about the same time.
#
# Brad Lhotsky <brad.lhotsky@gmail.com>
#
use strict;
use warnings;
use DateTime;

# crontab file to check
my $CRONTAB = $ARGV[0];
die "crontab doesn't exist: $CRONTAB" unless -f $CRONTAB;

# Track errors here.
my $ERROR = undef;

# Open the crontab file for reading
open my $FH, "<", $CRONTAB
    or $ERROR = "Unable to open $CRONTAB: $!";

# Determine modification time of the file
my $MOD;
eval {
    $MOD = DateTime->from_epoch( epoch => (stat $CRONTAB)[9], time_zone => "Europe/Amsterdam" );
};
if (defined $@ || !defined $MOD) {
    $ERROR = "Error parsing file modification time of '$CRONTAB'";
}

# Check for puppet managed
my $is_puppet_managed = undef;
if(! defined $ERROR ) {
    while( local $_ = <$FH> ) {
        chomp;                  # Trim trailing spaces
        next unless /^# HEADER: This file was autogenerated at (.*) by puppet.$/;
        my $dateStr = $1;
        $is_puppet_managed = 1;

        # Break the date string '2013-03-01 13:30:53 +0100' into pieces
        my @names = qw(year month day hour minute second time_zone);
        # This map {} translates the split pieces into K/V pairs named
        #  using the order of the @names array
        my %parts = map { shift @names => $_ } split /[ \-:]/, $dateStr;

        # Attempt to instantiate a DateTime object with the previous date string
        my $puppet_dt;
        eval {
            $puppet_dt = DateTime->new( %parts );
        };
        if($@ || !defined $puppet_dt) {
            # We failed, miserably
            $ERROR = "Puppet date unparseable";
            last;
        }

        # Figure out if the difference is greater than allowance
        my $max = DateTime::Duration->new( minutes => 1 );
        my $diff = $MOD->subtract_datetime( $puppet_dt );

        if( DateTime::Duration->compare( $diff, $max, $MOD ) > 0  ) {
            $ERROR = "puppet:" . $puppet_dt->datetime . " file:" . $MOD->datetime;
        }
        last;
    }
    if(!defined $is_puppet_managed) {
        $is_puppet_managed = 0;
        $ERROR = "Puppet modification headers not found";
    }
}
# Log the error for alerting
if( $ERROR ) {
    my $msg =  "$CRONTAB control:" . (defined $is_puppet_managed ? ($is_puppet_managed ? "puppet" : "unmanaged") : "unknown" ) . " - $ERROR";
    die $msg;
}
exit 0;
